In [192]:
from sklearn.cluster import KMeans
import pandas as pd

In [193]:
df =pd.read_csv(r'D:\Roshan raj Mahato\Desktop\Data Analytics\DATA_SCIENCE_SANTOSH_SIR\Datasets\Mall_Customers.csv')

In [194]:
df['Gender']=df['Gender'].map({'Male':1,'Female':0})

In [195]:
df.columns

Index(['CustomerID', 'Gender', 'Age', 'Annual Income (k$)',
       'Spending Score (1-100)'],
      dtype='object')

In [196]:
df.drop(columns='CustomerID',inplace=True)

In [197]:
df.head()

   Gender  Age  Annual Income (k$)  Spending Score (1-100)
0       1   19                  15                      39
1       1   21                  15                      81
2       0   20                  16                       6
3       0   23                  16                      77
4       0   31                  17                      40

In [198]:
model =KMeans(n_clusters=2,random_state=42)
model.fit_transform(df)

C:\Users\Roshan raj Mahato\AppData\Roaming\Python\Python312\site-packages\sklearn\cluster\_kmeans.py:1425: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(

array([[ 42.02783022,  83.95684707],
       [ 55.31675855,  77.89845208],
       [ 55.21259474, 100.34462535],
       [ 51.31016712,  76.1850959 ],
       [ 35.3593818 ,  80.40886458],
       [ 50.33737846,  75.28087741],
       [ 50.2765676 ,  97.8425717 ],
       [ 62.61491824,  77.46398413],
       [ 56.82738487, 103.52597341],
       [ 43.9306761 ,  72.25217762],
       [ 51.0631352 ,  97.62557129],
       [ 64.12833832,  77.37518231],
       [ 45.68696794,  93.61602696],
       [ 48.33010489,  72.09630483],
       [ 43.646566  ,  91.82185018],
       [ 50.42539134,  72.59908519],
       [ 31.58566609,  78.83158527],
       [ 42.5284312 ,  71.7144372 ],
       [ 33.60504485,  82.00077542],
       [ 61.34691334,  73.28655291],
       [ 28.76303525,  76.17634478],
       [ 42.68515812,  67.77722457],
       [ 46.86047697,  94.17648594],
       [ 40.26388727,  66.23256125],
       [ 39.87129408,  87.33915027],
       [ 46.10538942,  64.28518883],
       [ 26.11556477,  74.99168067],
       [ 29.24392131,  63.92054054],
       [ 25.29476932,  74.12125541],
       [ 51.58969284,  65.11465915],
       [ 48.93668398,  94.30823844],
       [ 40.91096349,  62.55599228],
       [ 45.29954789,  90.68260861],
       [ 56.20834446,  63.8791346 ],
       [ 35.69308627,  82.75467058],
       [ 45.72914062,  60.42766064],
       [ 31.59253888,  79.00080487],
       [ 35.431685  ,  57.31166696],
       [ 22.87573035,  70.41396999],
       [ 39.8891106 ,  56.0873768 ],
       [ 29.1488302 ,  71.20687352],
       [ 52.66187163,  58.02192548],
       [ 16.09622666,  64.29847461],
       [ 23.03936191,  53.17034421],
       [ 21.48062988,  69.1869605 ],
       [ 29.41864942,  53.44274666],
       [ 18.48851954,  55.86854067],
       [ 17.56031972,  56.92980037],
       [ 15.82208939,  59.00354936],
       [ 14.45670805,  58.86285334],
       [ 14.98847231,  54.72737435],
       [ 20.03474842,  50.35790739],
       [ 16.04341436,  51.13790672],
       [ 26.06008416,  55.27282789],
       [ 12.57018558,  56.95211881],
       [ 10.68553312,  58.15140156],
       [ 14.21994845,  54.27708697],
       [ 29.5852308 ,  63.72533905],
       [ 16.01304032,  49.87486511],
       [ 13.79822976,  54.92800291],
       [ 32.51694436,  59.55776331],
       [ 24.67465325,  50.21953972],
       [ 28.22226794,  58.20296817],
       [ 20.93747804,  49.85355725],
       [ 24.01527118,  55.61176887],
       [ 27.27316181,  47.58985014],
       [  7.50414532,  48.77843277],
       [ 28.16136   ,  59.45623463],
       [ 26.46042899,  47.25994255],
       [  9.45955864,  49.40186066],
       [ 31.83029155,  57.58799502],
       [  7.13564715,  52.73441795],
       [ 20.4092107 ,  53.32801487],
       [ 23.25282297,  50.84168733],
       [ 19.22434277,  50.71819697],
       [ 17.96880593,  41.64085138],
       [ 10.9218076 ,  42.66441339],
       [  5.39093656,  44.06673542],
       [ 19.50159473,  43.17023091],
       [  9.35395144,  49.39722162],
       [ 18.48958703,  47.96789381],
       [ 12.02340206,  40.61355074],
       [ 26.97750695,  57.9482715 ],
       [  6.47944825,  47.41266185],
       [ 23.71367776,  41.80014558],
       [  8.61510834,  46.85663066],
       [ 21.41990189,  42.0545539 ],
       [ 22.42200721,  39.60063766],
       [ 18.93573862,  34.90645361],
       [ 12.22741041,  44.42739962],
       [ 30.9878429 ,  49.33856338],
       [ 23.90791737,  46.82994594],
       [ 13.05893875,  40.55913999],
       [  9.80650091,  44.31941452],
       [ 12.45028375,  42.5974628 ],
       [ 20.49028235,  37.85556547],
       [ 11.77403867,  41.35418766],
       [ 17.35683051,  38.2230581 ],
       [ 12.78914372,  44.05444174],
       [ 23.33472874,  39.89937974],
       [ 20.75284602,  43.27434386],
       [ 14.74419019,  39.97606163],
       [ 32.71884355,  45.51925054],
       [ 21.40300243,  34.21930016],
       [ 18.74542996,  35.9757164 ],
       [ 22.35530285,  43.15381988],
       [ 29.07990964,  47.40123596],
       [ 18.40792413,  42.55048574],
       [ 30.20341715,  52.1676193 ],
       [ 28.71015018,  48.3222913 ],
       [ 28.72091824,  45.87303678],
       [ 26.62945712,  36.18819564],
       [ 13.40597224,  39.8972911 ],
       [ 25.15000444,  39.88110041],
       [ 26.77211997,  38.37156721],
       [ 26.3542983 ,  36.78431056],
       [ 26.69952862,  47.95051793],
       [ 22.5842653 ,  32.3625633 ],
       [ 19.32060768,  40.6232959 ],
       [ 23.04935408,  32.08650552],
       [ 24.29146671,  29.29878559],
       [ 16.66730449,  39.472064  ],
       [ 23.1103551 ,  26.32414298],
       [ 50.72652775,  30.2228198 ],
       [ 29.65319877,  48.31841095],
       [ 39.56402655,  22.18863456],
       [ 22.03637154,  42.18710905],
       [ 55.16181066,  31.86890601],
       [ 42.62840154,  67.99327543],
       [ 37.32868358,  20.88565305],
       [ 40.59260481,  66.44234722],
       [ 37.27947915,  21.09309927],
       [ 27.8032862 ,  42.64487664],
       [ 35.79468627,  19.38647734],
       [ 48.93157507,  69.89249247],
       [ 50.8459654 ,  25.38048141],
       [ 42.93672318,  67.24428479],
       [ 37.68755326,  18.37009808],
       [ 46.04170406,  65.14600656],
       [ 36.96864371,  17.18047836],
       [ 48.48436088,  71.68334653],
       [ 55.5648894 ,  27.36714277],
       [ 28.1987138 ,  35.03870008],
       [ 50.79483073,  22.12563755],
       [ 43.78171437,  61.35553903],
       [ 60.67501079,  30.22626623],
       [ 28.2504604 ,  40.20937499],
       [ 40.89890086,  14.60458273],
       [ 35.24551613,  50.72928645],
       [ 54.07824825,  23.10037165],
       [ 38.0871105 ,  56.27612433],
       [ 52.00603798,  22.02654845],
       [ 36.13948252,  53.57745642],
       [ 42.2770821 ,  14.57030668],
       [ 39.26960238,  57.98852332],
       [ 54.50057061,  23.39876429],
       [ 50.62474522,  71.27939513],
       [ 44.96880892,  15.44756195],
       [ 50.91048995,  71.2223783 ],
       [ 41.27359405,  13.91499803],
       [ 33.30535103,  43.82686205],
       [ 49.67628458,  17.82326673],
       [ 53.41763544,  68.47081254],
       [ 58.56729451,  24.42509987],
       [ 39.58347724,  48.10624183],
       [ 46.53220828,   7.55825179],
       [ 42.34363293,  51.8584018 ],
       [ 62.64328071,  24.57136891],
       [ 39.97807409,  44.23377861],
       [ 41.80385385,   9.27148874],
       [ 47.34291574,  58.4433672 ],
       [ 49.38712902,   8.43369256],
       [ 49.52600685,  61.17020383],
       [ 60.50823421,  21.48938894],
       [ 49.50129278,  60.76767647],
       [ 57.25321491,  15.87851284],
       [ 50.07924339,  60.95184304],
       [ 46.8777423 ,   8.07272177],
       [ 54.75804759,  62.2140298 ],
       [ 62.85339322,  19.12029036],
       [ 47.65607695,  39.54536008],
       [ 63.16048138,  16.2571165 ],
       [ 55.40600468,  57.65524408],
       [ 65.68803133,  19.05042878],
       [ 48.32125594,  33.66257324],
       [ 72.58214285,  27.48715767],
       [ 55.51158331,  51.96996412],
       [ 57.05707288,  12.0261037 ],
       [ 58.51042721,  55.71506831],
       [ 66.66281286,  18.45608762],
       [ 56.38784011,  49.44906979],
       [ 58.53909254,  12.23902924],
       [ 71.96634145,  66.7020902 ],
       [ 78.13355022,  29.89220361],
       [ 74.71170265,  63.43633688],
       [ 77.80303463,  29.97780574],
       [ 76.84483058,  56.420317  ],
       [ 81.43004157,  35.07435678],
       [ 90.21427176,  70.13173678],
       [ 95.23051859,  47.60298139]])

In [199]:
df['Result']=model.predict(df)

In [200]:
gp_result=df.groupby('Result')

In [201]:
# Cluster 1
gp_result.get_group(0)

     Gender  Age  Annual Income (k$)  Spending Score (1-100)  Result
0         1   19                  15                      39       0
1         1   21                  15                      81       0
2         0   20                  16                       6       0
3         0   23                  16                      77       0
4         0   31                  17                      40       0
..      ...  ...                 ...                     ...     ...
172       1   36                  87                      10       0
174       0   52                  88                      13       0
176       1   58                  88                      15       0
178       1   59                  93                      14       0
182       1   46                  98                      15       0

[152 rows x 5 columns]

In [202]:
gp_result.get_group(1)

     Gender  Age  Annual Income (k$)  Spending Score (1-100)  Result
123       1   39                  69                      91       1
125       0   31                  70                      77       1
127       1   40                  71                      95       1
129       1   38                  71                      75       1
131       1   39                  71                      75       1
133       0   31                  72                      71       1
135       0   29                  73                      88       1
137       1   32                  73                      73       1
139       0   35                  74                      72       1
141       1   32                  75                      93       1
143       0   32                  76                      87       1
145       1   28                  77                      97       1
147       0   32                  77                      74       1
149       1   34                  78                      90       1
151       1   39                  78                      88       1
153       0   38                  78                      76       1
155       0   27                  78                      89       1
157       0   30                  78                      78       1
159       0   30                  78                      73       1
161       0   29                  79                      83       1
163       0   31                  81                      93       1
165       0   36                  85                      75       1
167       0   33                  86                      95       1
169       1   32                  87                      63       1
171       1   28                  87                      75       1
173       1   36                  87                      92       1
175       0   30                  88                      86       1
177       1   27                  88                      69       1
179       1   35                  93                      90       1
180       0   37                  97                      32       1
181       0   32                  97                      86       1
183       0   29                  98                      88       1
184       0   41                  99                      39       1
185       1   30                  99                      97       1
186       0   54                 101                      24       1
187       1   28                 101                      68       1
188       0   41                 103                      17       1
189       0   36                 103                      85       1
190       0   34                 103                      23       1
191       0   32                 103                      69       1
192       1   33                 113                       8       1
193       0   38                 113                      91       1
194       0   47                 120                      16       1
195       0   35                 120                      79       1
196       0   45                 126                      28       1
197       1   32                 126                      74       1
198       1   32                 137                      18       1
199       1   30                 137                      83       1

In [203]:
model.cluster_centers_

array([[ 0.44736842, 40.33552632, 50.90789474, 43.63157895],
       [ 0.41666667, 34.14583333, 91.125     , 71.        ]])

In [204]:
model.n_iter_

3

In [205]:
# df['result']=model.predict(df)

In [206]:
df

     Gender  Age  Annual Income (k$)  Spending Score (1-100)  Result
0         1   19                  15                      39       0
1         1   21                  15                      81       0
2         0   20                  16                       6       0
3         0   23                  16                      77       0
4         0   31                  17                      40       0
..      ...  ...                 ...                     ...     ...
195       0   35                 120                      79       1
196       0   45                 126                      28       1
197       1   32                 126                      74       1
198       1   32                 137                      18       1
199       1   30                 137                      83       1

[200 rows x 5 columns]

In [207]:
import seaborn as sns 

# sns.scatterplot(data=df,x='Spending Score (1-100)',y='Spending Score(1-100)',hue='result')

## PCA :- Principle Components Analysis

In [208]:
from sklearn.decomposition import PCA

In [209]:
df

     Gender  Age  Annual Income (k$)  Spending Score (1-100)  Result
0         1   19                  15                      39       0
1         1   21                  15                      81       0
2         0   20                  16                       6       0
3         0   23                  16                      77       0
4         0   31                  17                      40       0
..      ...  ...                 ...                     ...     ...
195       0   35                 120                      79       1
196       0   45                 126                      28       1
197       1   32                 126                      74       1
198       1   32                 137                      18       1
199       1   30                 137                      83       1

[200 rows x 5 columns]

In [210]:
pca_=PCA(n_components=0.95) # 0.95 or 0.90

In [211]:
pca_values=pca_.fit_transform(df)

In [212]:
pca_values

array([[-3.19437535e+01, -3.29294878e+01, -2.21427401e+01],
       [ 6.35282641e-01, -5.68450055e+01, -1.05425945e+01],
       [-5.74360171e+01, -1.29954020e+01, -2.87505579e+01],
       [-2.29005787e+00, -5.34740685e+01, -9.51153429e+00],
       [-3.22420441e+01, -3.03159781e+01, -1.02248287e+01],
       [-2.29569049e+00, -5.22227434e+01, -1.07090869e+01],
       [-5.90853229e+01, -9.41046910e+00, -1.41414075e+01],
       [ 1.22301736e+01, -6.16464395e+01, -5.59305901e+00],
       [-6.63207394e+01, -3.06451677e+00,  1.33990736e+01],
       [-5.76300809e+00, -4.72548455e+01, -3.83180270e+00],
       [-5.82553178e+01, -9.00275803e+00,  1.88470580e+01],
       [ 1.44798833e+01, -6.21410868e+01,  7.24021036e+00],
       [-5.51819090e+01, -9.95547990e+00,  1.03220715e+01],
       [-1.17236402e-01, -5.01145130e+01, -8.51629686e+00],
       [-5.27895173e+01, -1.15617432e+01, -1.05735581e+01],
       [ 1.82912575e+00, -5.15270611e+01, -1.00015513e+01],
       [-3.45586111e+01, -2.36838838e+01, -7.45921727e+00],
       [-7.40394430e+00, -4.34990409e+01, -1.49305209e+01],
       [-4.12936402e+01, -1.63805490e+01,  7.71870987e+00],
       [ 1.60566992e+01, -5.83372476e+01,  7.03238805e+00],
       [-3.27878217e+01, -2.12611803e+01, -7.44123357e+00],
       [-1.08344677e+00, -4.44506831e+01, -8.43899961e+00],
       [-5.78127595e+01, -1.74021563e+00, -3.62740859e+00],
       [-1.62509453e+00, -4.28553016e+01, -2.59423801e+00],
       [-5.04889210e+01, -3.44903521e+00,  6.24344123e+00],
       [ 7.58544501e+00, -4.58780213e+01, -2.45547904e+00],
       [-3.46667288e+01, -1.49936729e+01,  1.62187122e+00],
       [-1.00247638e+01, -3.30005324e+01, -1.44308825e+00],
       [-3.39176810e+01, -1.42679078e+01, -3.46851777e+00],
       [ 1.32315460e+01, -4.87392682e+01, -7.14143564e+00],
       [-5.82872815e+01,  4.71170453e+00,  9.79666582e+00],
       [ 3.21380035e+00, -4.01355743e+01, -1.23002559e+01],
       [-5.51954721e+01,  6.21309858e+00,  3.00072348e+00],
       [ 2.04594370e+01, -4.90448421e+01, -1.08347370e+01],
       [-4.65937060e+01, -7.07784014e-02,  1.40493123e+00],
       [ 1.12623241e+01, -4.23198402e+01, -1.04449294e+01],
       [-4.23286155e+01, -1.91048836e+00, -4.71247332e+00],
       [ 3.87726094e+00, -3.57248987e+01, -3.51934576e+00],
       [-3.23633955e+01, -5.45876809e+00, -8.46655069e+00],
       [ 9.10443197e+00, -3.57690222e+01, -1.27752141e+01],
       [-3.01823751e+01, -6.02248020e+00,  2.18306757e+01],
       [ 2.22792808e+01, -4.42212952e+01, -4.96794708e+00],
       [-2.56002641e+01, -8.02316335e+00,  5.52294147e+00],
       [-2.77565222e+00, -2.46502168e+01, -5.27680909e+00],
       [-3.20660099e+01, -3.28796272e+00,  4.65588289e+00],
       [ 1.68374105e+00, -2.78726418e+01, -1.11698701e+01],
       [-1.04780652e+01, -1.78927227e+01,  1.18405667e+01],
       [-1.24160577e+01, -1.63093029e+01, -1.23820475e+01],
       [-1.67167760e+01, -1.31681541e+01, -1.15848826e+01],
       [-1.70941162e+01, -1.29053741e+01, -9.63846441e+00],
       [-1.14626762e+01, -1.46830087e+01,  1.01888198e+01],
       [-2.16687871e+00, -2.13890595e+01, -3.54225788e+00],
       [-5.90689004e+00, -1.73923350e+01, -6.86373532e+00],
       [-6.48192866e+00, -1.71658778e+01,  2.17666854e+01],
       [-1.65537028e+01, -9.71486102e+00,  9.55858142e+00],
       [-1.91267243e+01, -7.80475664e+00,  5.72101399e+00],
       [-1.22286218e+01, -1.16547984e+01,  1.16865509e+01],
       [-1.87637156e+01, -6.98550381e+00,  2.82863742e+01],
       [-5.73511780e+00, -1.37697497e+01, -1.14296024e+01],
       [-1.45642481e+01, -7.47366123e+00,  1.27260430e+01],
       [-9.92488369e+00, -1.09967686e+01,  3.15691040e+01],
       [-1.08738374e+00, -1.71219854e+01, -1.82944100e+01],
       [-1.19068737e+01, -8.28278163e+00,  2.77341188e+01],
       [-3.96143284e+00, -1.40205680e+01,  1.66913552e+01],
       [-1.13468253e+01, -7.42404715e+00,  2.36184013e+01],
       [ 3.42073466e+00, -1.79419876e+01, -1.83372023e+01],
       [-8.35776939e+00, -9.47775300e+00,  3.92290652e+00],
       [-1.46438734e+01, -5.04165524e+00,  2.77934323e+01],
       [ 3.23206455e+00, -1.78105976e+01, -1.73639932e+01],
       [-8.63642507e+00, -9.19602185e+00, -7.47194538e+00],
       [-8.93844064e+00, -7.99997072e+00,  3.13557746e+01],
       [-1.47994820e+01, -3.53976156e+00,  5.98244472e+00],
       [-1.11690911e+01, -5.05436633e+00,  2.02486245e+01],
       [-5.67636170e+00, -9.08408260e+00,  2.18575791e+01],
       [-1.01886100e+01, -8.04663938e-01,  1.88392049e+01],
       [ 1.53023301e+00, -9.17025055e+00, -1.16677404e+01],
       [-2.83884537e+00, -6.09974601e+00,  6.59191916e+00],
       [-5.81920228e+00, -3.87674789e+00,  5.78082910e-01],
       [ 5.27221411e-01, -8.41465248e+00, -1.50485314e+01],
       [-1.22249577e+01,  7.58225323e-01,  7.95639832e+00],
       [-6.67256726e+00, -3.37013897e+00,  1.78121893e+01],
       [ 5.08673262e-02, -8.16924418e+00,  2.40619312e-01],
       [-1.64060246e+01,  3.70049866e+00,  2.52457736e+01],
       [-1.00895961e+01, -7.87292215e-01,  5.49647237e+00],
       [ 4.82793976e+00, -1.15558013e+01, -1.58456963e+01],
       [-8.89791441e+00, -1.67428030e+00,  7.90405429e+00],
       [ 9.68950355e-01, -5.24309055e+00,  1.74897845e+01],
       [ 4.84103708e+00, -7.85193963e+00, -1.53156672e+01],
       [ 7.09074680e+00, -8.34658690e+00, -2.48239786e+00],
       [-6.91343373e+00,  1.81508581e+00,  9.87103836e+00],
       [-2.65704216e+00, -1.93916415e-01,  2.94629649e+01],
       [-4.20932480e+00,  1.29759502e+00, -2.24139361e+01],
       [-3.00165017e+00,  1.44094668e+00,  8.62664876e+00],
       [-8.55404061e+00,  5.56931097e+00, -1.22914224e+00],
       [-5.47532848e+00,  3.36684338e+00, -8.55511362e+00],
       [ 3.88045934e+00, -3.43943483e+00, -1.40408173e+01],
       [-4.38200199e+00,  2.45932477e+00,  7.19227593e+00],
       [ 1.74542708e+00, -1.89549670e+00, -1.15823538e+01],
       [-7.90400666e+00,  6.27770432e+00,  7.02320127e+00],
       [ 2.87148579e+00, -1.43093224e+00, -1.86176985e+01],
       [-3.38122734e+00,  4.37408979e+00, -1.75328319e+01],
       [-2.79392079e+00,  3.76051378e+00,  9.37955892e+00],
       [ 2.44111981e+00, -2.05297918e-01,  2.94271421e+01],
       [ 7.03789179e+00, -3.28959332e+00, -1.13938330e+01],
       [ 3.48315490e+00, -8.43296842e-01,  1.12198266e+01],
       [-2.21921149e+00,  3.53563602e+00, -1.92493994e+01],
       [-3.84158850e+00,  5.64983782e+00,  2.63893218e+01],
       [-4.71657903e+00,  6.37743212e+00,  1.37928726e+01],
       [-9.71198744e+00,  9.94391352e+00,  2.67282478e+01],
       [-5.41126908e+00,  6.80276473e+00,  2.59310829e+01],
       [-2.08389647e+00,  4.36867971e+00,  2.58772764e+01],
       [ 8.16460914e+00, -2.82818767e+00, -1.84321026e+01],
       [-4.24585756e+00,  7.38334893e+00, -2.69383076e+00],
       [ 2.47724770e+00,  2.58582313e+00, -2.02639383e+01],
       [ 4.82597128e+00,  2.10854758e+00, -2.07734015e+01],
       [ 6.20665242e+00,  1.08859008e+00, -1.93404911e+01],
       [-7.58756178e+00,  1.08994668e+01,  2.18717541e+01],
       [ 7.60862979e+00, -1.50773389e-01,  1.19244374e+01],
       [-4.14277468e+00,  1.09368694e+01,  1.02042593e+01],
       [ 7.03135421e+00,  2.74604687e+00,  1.24489593e+01],
       [ 1.05857618e+01,  3.01329794e-01, -1.01632379e+01],
       [-4.04409014e+00,  1.09558206e+01, -3.13701081e+00],
       [ 1.08834767e+01,  2.47055576e+00,  2.95773329e+00],
       [ 3.69782577e+01, -1.66522315e+01,  9.57159397e+00],
       [-8.07435172e+00,  1.77385058e+01, -2.02469830e+01],
       [ 2.80928620e+01, -8.83845711e+00, -1.42794321e+00],
       [-6.54965657e+00,  1.77208843e+01,  6.03272129e-01],
       [ 4.11090359e+01, -1.72094538e+01,  1.14752198e+01],
       [-2.84005934e+01,  3.36392945e+01,  1.06582018e+01],
       [ 2.57928635e+01, -5.95875876e+00,  4.93178860e+00],
       [-2.77059033e+01,  3.32139619e+01, -1.48000851e+00],
       [ 2.56041934e+01, -5.82736875e+00,  5.90499769e+00],
       [-3.34756801e+00,  1.67369998e+01, -1.71402974e+01],
       [ 2.45655540e+01, -3.77033185e+00, -2.79603296e+00],
       [-2.45697671e+01,  3.35832094e+01, -2.86650423e+01],
       [ 3.88727528e+01, -1.30125243e+01, -8.29482941e-01],
       [-2.75281691e+01,  3.55836427e+01, -4.84978534e+00],
       [ 2.65362787e+01, -3.98166857e+00, -1.35615304e+00],
       [-1.98673459e+01,  3.13804920e+01, -2.84834910e+01],
       [ 2.57762950e+01, -2.20636281e+00,  1.33766821e+00],
       [-3.03694860e+01,  4.00571431e+01,  7.35324563e+00],
       [ 4.34105370e+01, -1.38810609e+01,  3.25187419e+00],
       [ 3.15596700e+00,  1.69052928e+01, -1.28195379e+01],
       [ 3.92931855e+01, -9.62155640e+00,  1.87681492e+00],
       [-1.76588967e+01,  3.34386087e+01, -2.21680139e+01],
       [ 4.84846658e+01, -1.50952332e+01,  2.89454634e-01],
       [-3.16609413e+00,  2.26444088e+01,  5.73221072e+00],
       [ 2.96827752e+01, -1.33075623e+00, -1.10573649e+00],
       [-1.09194692e+01,  2.96698432e+01, -1.11065810e+01],
       [ 4.24502886e+01, -9.47013549e+00,  4.52526166e+00],
       [-1.65412076e+01,  3.37323014e+01, -3.49549003e+00],
       [ 3.99375868e+01, -7.66183794e+00,  8.93160578e+00],
       [-1.43755215e+01,  3.21350908e+01, -1.83419142e+00],
       [ 3.07104787e+01, -8.86722307e-01,  5.19872642e+00],
       [-1.80802343e+01,  3.48319558e+01,  1.66033220e-01],
       [ 4.29866331e+01, -9.81577122e+00, -2.51851503e+00],
       [-2.79639970e+01,  4.21547414e+01, -1.30123550e+01],
       [ 3.37891909e+01, -3.08918990e+00, -2.12724496e+00],
       [-2.73979867e+01,  4.17605714e+01, -1.59319822e+01],
       [ 2.98658127e+01, -2.10821129e-01, -3.27649823e+00],
       [-4.27905552e+00,  2.58837060e+01,  1.32975845e+01],
       [ 3.84916120e+01, -5.29190730e+00, -1.94569369e+00],
       [-1.96581138e+01,  3.99081504e+01, -2.95941947e+01],
       [ 4.71417738e+01, -9.17178207e+00,  2.31024518e+00],
       [-6.66720747e+00,  3.51202573e+01,  5.42417905e+00],
       [ 3.44357536e+01,  5.07546103e+00,  3.06100719e+00],
       [-9.27552747e+00,  3.83302211e+01, -3.73509047e+00],
       [ 5.12856493e+01, -6.02514270e+00,  4.74390008e+00],
       [-2.06007520e+00,  3.43176268e+01, -7.96134576e+00],
       [ 2.69547430e+01,  1.30736482e+01, -3.57756038e+00],
       [-1.38005437e+01,  4.29041988e+01, -7.28495613e+00],
       [ 3.71255309e+01,  5.64000310e+00, -4.71218888e+00],
       [-1.53998902e+01,  4.41056600e+01, -1.18673444e+01],
       [ 4.89556557e+01, -3.09533063e+00,  6.98094491e+00],
       [-1.54738828e+01,  4.52863409e+01,  4.39759754e+00],
       [ 4.59703248e+01,  3.75833800e-01, -2.33368878e-01],
       [-1.50368816e+01,  4.49249128e+01,  1.06980158e+01],
       [ 3.31965202e+01,  9.76969698e+00, -7.05899480e+00],
       [-1.30583628e+01,  4.96671835e+01,  1.14689097e+01],
       [ 5.11172119e+01,  2.76687510e+00,  5.58107703e+00],
       [ 7.59050623e+00,  3.96453189e+01, -5.78327678e+00],
       [ 5.09063406e+01,  7.90198617e+00,  1.76261306e+00],
       [-6.86911132e+00,  5.14186464e+01, -9.25422368e-01],
       [ 5.36320751e+01,  7.16351001e+00, -6.91805801e-01],
       [ 1.35093010e+01,  3.77552454e+01, -2.70471698e-01],
       [ 6.10955292e+01,  2.92245701e+00,  2.35702869e+00],
       [ 4.67200929e-01,  4.97125046e+01,  8.94450078e+00],
       [ 3.98980220e+01,  2.09682986e+01, -6.24404425e+00],
       [-1.39207125e+00,  5.36482335e+01, -5.30515773e+00],
       [ 5.29092219e+01,  1.38454682e+01,  5.45864126e+00],
       [ 4.63667328e+00,  4.92744609e+01, -1.07385174e+01],
       [ 4.11090923e+01,  2.25306882e+01, -2.11180553e+00],
       [-1.04139141e+00,  6.58501703e+01, -1.51029530e+01],
       [ 6.31436644e+01,  1.87246194e+01,  8.83923421e+00],
       [ 6.72757166e+00,  6.87319506e+01,  3.97866587e-01],
       [ 5.84261775e+01,  3.08878240e+01,  3.19994871e+00],
       [ 2.00632568e+01,  6.64033338e+01,  1.24269877e+00],
       [ 5.86107177e+01,  3.82158504e+01, -8.34426854e-01],
       [ 2.11629844e+01,  7.93310357e+01, -1.36454855e+01],
       [ 7.25442404e+01,  4.16494617e+01, -6.51611205e-01]])

In [213]:
pca_.explained_variance_

array([700.36763787, 684.34432317, 167.22892903])

In [214]:
pca_.explained_variance_ratio_

array([0.45119397, 0.44087136, 0.10773297])

In [215]:
df.head()

   Gender  Age  Annual Income (k$)  Spending Score (1-100)  Result
0       1   19                  15                      39       0
1       1   21                  15                      81       0
2       0   20                  16                       6       0
3       0   23                  16                      77       0
4       0   31                  17                      40       0

In [216]:
df.drop(columns=['Result'],inplace=True)

In [217]:
df

     Gender  Age  Annual Income (k$)  Spending Score (1-100)
0         1   19                  15                      39
1         1   21                  15                      81
2         0   20                  16                       6
3         0   23                  16                      77
4         0   31                  17                      40
..      ...  ...                 ...                     ...
195       0   35                 120                      79
196       0   45                 126                      28
197       1   32                 126                      74
198       1   32                 137                      18
199       1   30                 137                      83

[200 rows x 4 columns]

In [218]:
clusters=model.predict(df)

In [219]:
import seaborn as sns

In [220]:
pca_values

array([[-3.19437535e+01, -3.29294878e+01, -2.21427401e+01],
       [ 6.35282641e-01, -5.68450055e+01, -1.05425945e+01],
       [-5.74360171e+01, -1.29954020e+01, -2.87505579e+01],
       [-2.29005787e+00, -5.34740685e+01, -9.51153429e+00],
       [-3.22420441e+01, -3.03159781e+01, -1.02248287e+01],
       [-2.29569049e+00, -5.22227434e+01, -1.07090869e+01],
       [-5.90853229e+01, -9.41046910e+00, -1.41414075e+01],
       [ 1.22301736e+01, -6.16464395e+01, -5.59305901e+00],
       [-6.63207394e+01, -3.06451677e+00,  1.33990736e+01],
       [-5.76300809e+00, -4.72548455e+01, -3.83180270e+00],
       [-5.82553178e+01, -9.00275803e+00,  1.88470580e+01],
       [ 1.44798833e+01, -6.21410868e+01,  7.24021036e+00],
       [-5.51819090e+01, -9.95547990e+00,  1.03220715e+01],
       [-1.17236402e-01, -5.01145130e+01, -8.51629686e+00],
       [-5.27895173e+01, -1.15617432e+01, -1.05735581e+01],
       [ 1.82912575e+00, -5.15270611e+01, -1.00015513e+01],
       [-3.45586111e+01, -2.36838838e+01, -7.45921727e+00],
       [-7.40394430e+00, -4.34990409e+01, -1.49305209e+01],
       [-4.12936402e+01, -1.63805490e+01,  7.71870987e+00],
       [ 1.60566992e+01, -5.83372476e+01,  7.03238805e+00],
       [-3.27878217e+01, -2.12611803e+01, -7.44123357e+00],
       [-1.08344677e+00, -4.44506831e+01, -8.43899961e+00],
       [-5.78127595e+01, -1.74021563e+00, -3.62740859e+00],
       [-1.62509453e+00, -4.28553016e+01, -2.59423801e+00],
       [-5.04889210e+01, -3.44903521e+00,  6.24344123e+00],
       [ 7.58544501e+00, -4.58780213e+01, -2.45547904e+00],
       [-3.46667288e+01, -1.49936729e+01,  1.62187122e+00],
       [-1.00247638e+01, -3.30005324e+01, -1.44308825e+00],
       [-3.39176810e+01, -1.42679078e+01, -3.46851777e+00],
       [ 1.32315460e+01, -4.87392682e+01, -7.14143564e+00],
       [-5.82872815e+01,  4.71170453e+00,  9.79666582e+00],
       [ 3.21380035e+00, -4.01355743e+01, -1.23002559e+01],
       [-5.51954721e+01,  6.21309858e+00,  3.00072348e+00],
       [ 2.04594370e+01, -4.90448421e+01, -1.08347370e+01],
       [-4.65937060e+01, -7.07784014e-02,  1.40493123e+00],
       [ 1.12623241e+01, -4.23198402e+01, -1.04449294e+01],
       [-4.23286155e+01, -1.91048836e+00, -4.71247332e+00],
       [ 3.87726094e+00, -3.57248987e+01, -3.51934576e+00],
       [-3.23633955e+01, -5.45876809e+00, -8.46655069e+00],
       [ 9.10443197e+00, -3.57690222e+01, -1.27752141e+01],
       [-3.01823751e+01, -6.02248020e+00,  2.18306757e+01],
       [ 2.22792808e+01, -4.42212952e+01, -4.96794708e+00],
       [-2.56002641e+01, -8.02316335e+00,  5.52294147e+00],
       [-2.77565222e+00, -2.46502168e+01, -5.27680909e+00],
       [-3.20660099e+01, -3.28796272e+00,  4.65588289e+00],
       [ 1.68374105e+00, -2.78726418e+01, -1.11698701e+01],
       [-1.04780652e+01, -1.78927227e+01,  1.18405667e+01],
       [-1.24160577e+01, -1.63093029e+01, -1.23820475e+01],
       [-1.67167760e+01, -1.31681541e+01, -1.15848826e+01],
       [-1.70941162e+01, -1.29053741e+01, -9.63846441e+00],
       [-1.14626762e+01, -1.46830087e+01,  1.01888198e+01],
       [-2.16687871e+00, -2.13890595e+01, -3.54225788e+00],
       [-5.90689004e+00, -1.73923350e+01, -6.86373532e+00],
       [-6.48192866e+00, -1.71658778e+01,  2.17666854e+01],
       [-1.65537028e+01, -9.71486102e+00,  9.55858142e+00],
       [-1.91267243e+01, -7.80475664e+00,  5.72101399e+00],
       [-1.22286218e+01, -1.16547984e+01,  1.16865509e+01],
       [-1.87637156e+01, -6.98550381e+00,  2.82863742e+01],
       [-5.73511780e+00, -1.37697497e+01, -1.14296024e+01],
       [-1.45642481e+01, -7.47366123e+00,  1.27260430e+01],
       [-9.92488369e+00, -1.09967686e+01,  3.15691040e+01],
       [-1.08738374e+00, -1.71219854e+01, -1.82944100e+01],
       [-1.19068737e+01, -8.28278163e+00,  2.77341188e+01],
       [-3.96143284e+00, -1.40205680e+01,  1.66913552e+01],
       [-1.13468253e+01, -7.42404715e+00,  2.36184013e+01],
       [ 3.42073466e+00, -1.79419876e+01, -1.83372023e+01],
       [-8.35776939e+00, -9.47775300e+00,  3.92290652e+00],
       [-1.46438734e+01, -5.04165524e+00,  2.77934323e+01],
       [ 3.23206455e+00, -1.78105976e+01, -1.73639932e+01],
       [-8.63642507e+00, -9.19602185e+00, -7.47194538e+00],
       [-8.93844064e+00, -7.99997072e+00,  3.13557746e+01],
       [-1.47994820e+01, -3.53976156e+00,  5.98244472e+00],
       [-1.11690911e+01, -5.05436633e+00,  2.02486245e+01],
       [-5.67636170e+00, -9.08408260e+00,  2.18575791e+01],
       [-1.01886100e+01, -8.04663938e-01,  1.88392049e+01],
       [ 1.53023301e+00, -9.17025055e+00, -1.16677404e+01],
       [-2.83884537e+00, -6.09974601e+00,  6.59191916e+00],
       [-5.81920228e+00, -3.87674789e+00,  5.78082910e-01],
       [ 5.27221411e-01, -8.41465248e+00, -1.50485314e+01],
       [-1.22249577e+01,  7.58225323e-01,  7.95639832e+00],
       [-6.67256726e+00, -3.37013897e+00,  1.78121893e+01],
       [ 5.08673262e-02, -8.16924418e+00,  2.40619312e-01],
       [-1.64060246e+01,  3.70049866e+00,  2.52457736e+01],
       [-1.00895961e+01, -7.87292215e-01,  5.49647237e+00],
       [ 4.82793976e+00, -1.15558013e+01, -1.58456963e+01],
       [-8.89791441e+00, -1.67428030e+00,  7.90405429e+00],
       [ 9.68950355e-01, -5.24309055e+00,  1.74897845e+01],
       [ 4.84103708e+00, -7.85193963e+00, -1.53156672e+01],
       [ 7.09074680e+00, -8.34658690e+00, -2.48239786e+00],
       [-6.91343373e+00,  1.81508581e+00,  9.87103836e+00],
       [-2.65704216e+00, -1.93916415e-01,  2.94629649e+01],
       [-4.20932480e+00,  1.29759502e+00, -2.24139361e+01],
       [-3.00165017e+00,  1.44094668e+00,  8.62664876e+00],
       [-8.55404061e+00,  5.56931097e+00, -1.22914224e+00],
       [-5.47532848e+00,  3.36684338e+00, -8.55511362e+00],
       [ 3.88045934e+00, -3.43943483e+00, -1.40408173e+01],
       [-4.38200199e+00,  2.45932477e+00,  7.19227593e+00],
       [ 1.74542708e+00, -1.89549670e+00, -1.15823538e+01],
       [-7.90400666e+00,  6.27770432e+00,  7.02320127e+00],
       [ 2.87148579e+00, -1.43093224e+00, -1.86176985e+01],
       [-3.38122734e+00,  4.37408979e+00, -1.75328319e+01],
       [-2.79392079e+00,  3.76051378e+00,  9.37955892e+00],
       [ 2.44111981e+00, -2.05297918e-01,  2.94271421e+01],
       [ 7.03789179e+00, -3.28959332e+00, -1.13938330e+01],
       [ 3.48315490e+00, -8.43296842e-01,  1.12198266e+01],
       [-2.21921149e+00,  3.53563602e+00, -1.92493994e+01],
       [-3.84158850e+00,  5.64983782e+00,  2.63893218e+01],
       [-4.71657903e+00,  6.37743212e+00,  1.37928726e+01],
       [-9.71198744e+00,  9.94391352e+00,  2.67282478e+01],
       [-5.41126908e+00,  6.80276473e+00,  2.59310829e+01],
       [-2.08389647e+00,  4.36867971e+00,  2.58772764e+01],
       [ 8.16460914e+00, -2.82818767e+00, -1.84321026e+01],
       [-4.24585756e+00,  7.38334893e+00, -2.69383076e+00],
       [ 2.47724770e+00,  2.58582313e+00, -2.02639383e+01],
       [ 4.82597128e+00,  2.10854758e+00, -2.07734015e+01],
       [ 6.20665242e+00,  1.08859008e+00, -1.93404911e+01],
       [-7.58756178e+00,  1.08994668e+01,  2.18717541e+01],
       [ 7.60862979e+00, -1.50773389e-01,  1.19244374e+01],
       [-4.14277468e+00,  1.09368694e+01,  1.02042593e+01],
       [ 7.03135421e+00,  2.74604687e+00,  1.24489593e+01],
       [ 1.05857618e+01,  3.01329794e-01, -1.01632379e+01],
       [-4.04409014e+00,  1.09558206e+01, -3.13701081e+00],
       [ 1.08834767e+01,  2.47055576e+00,  2.95773329e+00],
       [ 3.69782577e+01, -1.66522315e+01,  9.57159397e+00],
       [-8.07435172e+00,  1.77385058e+01, -2.02469830e+01],
       [ 2.80928620e+01, -8.83845711e+00, -1.42794321e+00],
       [-6.54965657e+00,  1.77208843e+01,  6.03272129e-01],
       [ 4.11090359e+01, -1.72094538e+01,  1.14752198e+01],
       [-2.84005934e+01,  3.36392945e+01,  1.06582018e+01],
       [ 2.57928635e+01, -5.95875876e+00,  4.93178860e+00],
       [-2.77059033e+01,  3.32139619e+01, -1.48000851e+00],
       [ 2.56041934e+01, -5.82736875e+00,  5.90499769e+00],
       [-3.34756801e+00,  1.67369998e+01, -1.71402974e+01],
       [ 2.45655540e+01, -3.77033185e+00, -2.79603296e+00],
       [-2.45697671e+01,  3.35832094e+01, -2.86650423e+01],
       [ 3.88727528e+01, -1.30125243e+01, -8.29482941e-01],
       [-2.75281691e+01,  3.55836427e+01, -4.84978534e+00],
       [ 2.65362787e+01, -3.98166857e+00, -1.35615304e+00],
       [-1.98673459e+01,  3.13804920e+01, -2.84834910e+01],
       [ 2.57762950e+01, -2.20636281e+00,  1.33766821e+00],
       [-3.03694860e+01,  4.00571431e+01,  7.35324563e+00],
       [ 4.34105370e+01, -1.38810609e+01,  3.25187419e+00],
       [ 3.15596700e+00,  1.69052928e+01, -1.28195379e+01],
       [ 3.92931855e+01, -9.62155640e+00,  1.87681492e+00],
       [-1.76588967e+01,  3.34386087e+01, -2.21680139e+01],
       [ 4.84846658e+01, -1.50952332e+01,  2.89454634e-01],
       [-3.16609413e+00,  2.26444088e+01,  5.73221072e+00],
       [ 2.96827752e+01, -1.33075623e+00, -1.10573649e+00],
       [-1.09194692e+01,  2.96698432e+01, -1.11065810e+01],
       [ 4.24502886e+01, -9.47013549e+00,  4.52526166e+00],
       [-1.65412076e+01,  3.37323014e+01, -3.49549003e+00],
       [ 3.99375868e+01, -7.66183794e+00,  8.93160578e+00],
       [-1.43755215e+01,  3.21350908e+01, -1.83419142e+00],
       [ 3.07104787e+01, -8.86722307e-01,  5.19872642e+00],
       [-1.80802343e+01,  3.48319558e+01,  1.66033220e-01],
       [ 4.29866331e+01, -9.81577122e+00, -2.51851503e+00],
       [-2.79639970e+01,  4.21547414e+01, -1.30123550e+01],
       [ 3.37891909e+01, -3.08918990e+00, -2.12724496e+00],
       [-2.73979867e+01,  4.17605714e+01, -1.59319822e+01],
       [ 2.98658127e+01, -2.10821129e-01, -3.27649823e+00],
       [-4.27905552e+00,  2.58837060e+01,  1.32975845e+01],
       [ 3.84916120e+01, -5.29190730e+00, -1.94569369e+00],
       [-1.96581138e+01,  3.99081504e+01, -2.95941947e+01],
       [ 4.71417738e+01, -9.17178207e+00,  2.31024518e+00],
       [-6.66720747e+00,  3.51202573e+01,  5.42417905e+00],
       [ 3.44357536e+01,  5.07546103e+00,  3.06100719e+00],
       [-9.27552747e+00,  3.83302211e+01, -3.73509047e+00],
       [ 5.12856493e+01, -6.02514270e+00,  4.74390008e+00],
       [-2.06007520e+00,  3.43176268e+01, -7.96134576e+00],
       [ 2.69547430e+01,  1.30736482e+01, -3.57756038e+00],
       [-1.38005437e+01,  4.29041988e+01, -7.28495613e+00],
       [ 3.71255309e+01,  5.64000310e+00, -4.71218888e+00],
       [-1.53998902e+01,  4.41056600e+01, -1.18673444e+01],
       [ 4.89556557e+01, -3.09533063e+00,  6.98094491e+00],
       [-1.54738828e+01,  4.52863409e+01,  4.39759754e+00],
       [ 4.59703248e+01,  3.75833800e-01, -2.33368878e-01],
       [-1.50368816e+01,  4.49249128e+01,  1.06980158e+01],
       [ 3.31965202e+01,  9.76969698e+00, -7.05899480e+00],
       [-1.30583628e+01,  4.96671835e+01,  1.14689097e+01],
       [ 5.11172119e+01,  2.76687510e+00,  5.58107703e+00],
       [ 7.59050623e+00,  3.96453189e+01, -5.78327678e+00],
       [ 5.09063406e+01,  7.90198617e+00,  1.76261306e+00],
       [-6.86911132e+00,  5.14186464e+01, -9.25422368e-01],
       [ 5.36320751e+01,  7.16351001e+00, -6.91805801e-01],
       [ 1.35093010e+01,  3.77552454e+01, -2.70471698e-01],
       [ 6.10955292e+01,  2.92245701e+00,  2.35702869e+00],
       [ 4.67200929e-01,  4.97125046e+01,  8.94450078e+00],
       [ 3.98980220e+01,  2.09682986e+01, -6.24404425e+00],
       [-1.39207125e+00,  5.36482335e+01, -5.30515773e+00],
       [ 5.29092219e+01,  1.38454682e+01,  5.45864126e+00],
       [ 4.63667328e+00,  4.92744609e+01, -1.07385174e+01],
       [ 4.11090923e+01,  2.25306882e+01, -2.11180553e+00],
       [-1.04139141e+00,  6.58501703e+01, -1.51029530e+01],
       [ 6.31436644e+01,  1.87246194e+01,  8.83923421e+00],
       [ 6.72757166e+00,  6.87319506e+01,  3.97866587e-01],
       [ 5.84261775e+01,  3.08878240e+01,  3.19994871e+00],
       [ 2.00632568e+01,  6.64033338e+01,  1.24269877e+00],
       [ 5.86107177e+01,  3.82158504e+01, -8.34426854e-01],
       [ 2.11629844e+01,  7.93310357e+01, -1.36454855e+01],
       [ 7.25442404e+01,  4.16494617e+01, -6.51611205e-01]])