In [12]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,root_mean_squared_error,r2_score
from sklearn.model_selection import train_test_split

In [13]:
df=pd.read_csv(r"D:\Roshan raj Mahato\Desktop\Data Analytics\DATA_SCIENCE_SANTOSH_SIR\Datasets\student_performance.csv")

In [14]:
df.head()

   Hours Studied  ...  Performance Index
0              7  ...               91.0
1              4  ...               65.0
2              8  ...               45.0
3              5  ...               36.0
4              7  ...               66.0

[5 rows x 6 columns]

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     10000 non-null  int64
 1   Previous Scores                   10000 non-null  int64
 2   Extracurricular Activities        10000 non-null  object
 3   Sleep Hours                       10000 non-null  int64
 4   Sample Question Papers Practiced  10000 non-null  int64
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 468.9+ KB

In [16]:
df.columns

Index(['Hours Studied', 'Previous Scores', 'Extracurricular Activities',
       'Sleep Hours', 'Sample Question Papers Practiced', 'Performance Index'],
      dtype='object')

In [17]:
df['Extracurricular Activities']=df['Extracurricular Activities'].map({
    'Yes':1,
    'No':0,
})

In [18]:
df['Extracurricular Activities']

0       1
1       0
2       1
3       1
4       0
       ..
9995    1
9996    1
9997    1
9998    1
9999    0
Name: Extracurricular Activities, Length: 10000, dtype: int64

In [19]:
df

      Hours Studied  ...  Performance Index
0                 7  ...               91.0
1                 4  ...               65.0
2                 8  ...               45.0
3                 5  ...               36.0
4                 7  ...               66.0
...             ...  ...                ...
9995              1  ...               23.0
9996              7  ...               58.0
9997              6  ...               74.0
9998              9  ...               95.0
9999              7  ...               64.0

[10000 rows x 6 columns]

In [20]:
X=df.drop('Performance Index',axis=1)
y=df['Performance Index']

In [21]:
X

      Hours Studied  ...  Sample Question Papers Practiced
0                 7  ...                                 1
1                 4  ...                                 2
2                 8  ...                                 2
3                 5  ...                                 2
4                 7  ...                                 5
...             ...  ...                               ...
9995              1  ...                                 2
9996              7  ...                                 5
9997              6  ...                                 5
9998              9  ...                                 0
9999              7  ...                                 1

[10000 rows x 5 columns]

In [22]:
y

0       91.0
1       65.0
2       45.0
3       36.0
4       66.0
        ...
9995    23.0
9996    58.0
9997    74.0
9998    95.0
9999    64.0
Name: Performance Index, Length: 10000, dtype: float64

In [23]:
Xtrain,ytrain,Xtest,ytest=train_test_split(X,y,random_state=42)

In [24]:
Xtrain

      Hours Studied  ...  Sample Question Papers Practiced
4901              5  ...                                 5
4375              7  ...                                 9
6698              3  ...                                 1
9805              9  ...                                 9
1101              4  ...                                 6
...             ...  ...                               ...
5734              8  ...                                 6
5191              4  ...                                 3
5390              9  ...                                 6
860               1  ...                                 0
7270              2  ...                                 6

[7500 rows x 5 columns]

In [25]:
ytrain

      Hours Studied  ...  Sample Question Papers Practiced
6252              5  ...                                 2
4684              2  ...                                 8
1731              7  ...                                 5
4742              6  ...                                 5
4521              7  ...                                 6
...             ...  ...                               ...
4862              6  ...                                 4
7025              2  ...                                 2
7647              5  ...                                 8
7161              4  ...                                 3
73                8  ...                                 2

[2500 rows x 5 columns]